### ISSUE TITLE
Paginator not working on ReqbazRequirementsGrid component

### ISSUE THREAD

**Issue by lakhoune** [rwth-acis/RequirementsBazaar-Components#15] opened 2022-04-19 15:10 UTC
It seems like the paginator is broken for the ReqbazRequirementsGrid component. In my case the page was just increasing constantly without an end even though there was only 1 requirement 
![image](https://user-images.githubusercontent.com/38857665/164036153-8f0ed77e-2cee-498a-917d-4e670ee78cd6.png)

**Comment by fxjordan** [comment] 2022-04-23 09:54
Caused by https://github.com/rwth-acis/RequirementsBazaar/issues/155. The pagination of the API seems to be completely broken.

**Comment by fxjordan** [comment] 2022-04-23 12:45
Should be fixed by backend update https://github.com/rwth-acis/RequirementsBazaar/releases/tag/v0.12.3 (already deployed). Can you confirm @lakhoune ?

**Comment by lakhoune** [comment] 2022-04-23 12:55
Yes it is fixed thanks

**Closed as completed** 2022-04-23 12:56 UTC
Labels: bug
